# Generated by Django 3.1.2 on 2021-01-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('current_price', models.IntegerField()),
                ('current_date', models.CharField(max_length=100)),
                ('s1_date', models.CharField(max_length=100)),
                ('s1_price', models.IntegerField()),
                ('s1_diff', models.IntegerField()),
                ('s2_date', models.CharField(max_length=100)),
                ('s2_price', models.IntegerField()),
                ('s2_diff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
